### ISSUE TITLE
contact.html is missing the <form> tag and other things

### ISSUE THREAD

**Issue by billdavisjr** [Code-Institute-Solutions/InteractiveFrontendDevelopment-Resume#1]
The file contact.html in the 5-preparing_the_contact_html_file folder is missing the form tag.  It has the /form but not the open tag and the onsubmit and other params.  Also the  sendEmail.js is missing and the script tag this video added at the bottom of contact.html that loads it is missing.  The anonymous function in the script at the top in the head tag block that calls EmailJS.init() etc isn't matching the code in video either.

**Comment by NielMc** [comment]
Matched code to the video lesson
